### ISSUE TITLE
mup deploy error

### ISSUE THREAD

**Issue by najashark** [guidouil/TorrentsDuck#5]
I have followed instructions based on here https://github.com/guidouil/TorrentsDuck/blob/master/_docs/mupDeploy.md

but its seems to failed on `mup deploy`
`mup setup` is running just fine

```
ggrip@GGREAP:~/TorrentsDuck/.deploy/duck$ mup deploy
Building App Bundle Locally

Unable to resolve some modules:

  "@babel/runtime/helpers/interopRequireDefault" in
/home/ggrip/TorrentsDuck/duck/client/lib/semantic-ui/definitions/modules/dimmer.js
(web.browser.legacy)
  "@babel/runtime/helpers/typeof" in
/home/ggrip/TorrentsDuck/duck/client/lib/semantic-ui/definitions/modules/dimmer.js
(web.browser.legacy)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save @babel/runtime


Unable to resolve some modules:

  "diskusage" in /home/ggrip/TorrentsDuck/duck/imports/api/system/methods.js
(os.linux.x86_64)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save diskusage

Errors prevented bundling:
While minifying app stylesheet:
module.js:547:15: Cannot find module 'autoprefixer'
at Function.Module._resolveFilename (module.js:547:15)
at Function.resolve (internal/module.js:18:19)
at Object.require (/tools/isobuild/bundler.js:1927:34)
at packages/minifier-postcss/plugin/minify-css.js:52:37
at Array.forEach (<anonymous>)
at getPostCSSPlugins (packages/minifier-postcss/plugin/minify-css.js:51:43)
at packages/minifier-postcss/plugin/minify-css.js:155:36
at Array.map (<anonymous>)
at mergeCss (packages/minifier-postcss/plugin/minify-css.js:139:23)
at CssToolsMinifier.processFilesForBundle
(packages/minifier-postcss/plugin/minify-css.js:109:18)


While minifying app stylesheet:
module.js:547:15: Cannot find module 'autoprefixer'
at Function.Module._resolveFilename (module.js:547:15)
at Function.resolve (internal/module.js:18:19)
at Object.require (/tools/isobuild/bundler.js:1927:34)
at packages/minifier-postcss/plugin/minify-css.js:52:37
at Array.forEach (<anonymous>)
at getPostCSSPlugins (packages/minifier-postcss/plugin/minify-css.js:51:43)
at packages/minifier-postcss/plugin/minify-css.js:155:36
at Array.map (<anonymous>)
at mergeCss (packages/minifier-postcss/plugin/minify-css.js:139:23)
at CssToolsMinifier.processFilesForBundle
(packages/minifier-postcss/plugin/minify-css.js:109:18)



=> Build Error. Check the logs printed above.
```

I already run the said fix called 
```bash
meteor npm install --save @babel/runtime
```

```bash
meteor npm install --save diskusage
```
but this same error still occur

**Comment by guidouil** [comment]
did you `meteor npm install` locally first ? It might be part of the issue here 🤔 
and maybe first thing is to check if the main Meteor (`/duck` folder) runs on your computer.

**Comment by najashark** [comment]
yeah, i missed that command, thanks for pointing that out, now it works.

Just a question, can this be run without docker? because my server does not support docker.

**Comment by guidouil** [comment]
I think you can run it how you want it, for me it was more easy to deploy using mup but you can build it old school style for each meteor and run each with something like `forever` or `pm2`.
You can have a look at [this old gist](https://gist.github.com/guidouil/ff842e3857569c8fbe9dfd74b811e582), it might help you on your quest, or join the [Gitter Meteor channel](https://gitter.im/meteor/meteor)
